.TH DIARY 1
.SH NAME
diary \- Simple text-based diary program

.SH SYNOPSIS
.B diary
[\fIOPTION\fR]... [\fIDIRECTORY\fR]...
.br

.SH DESCRIPTION
.B diary
is a simple text-based program for managing journal entries.

.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-version\fR
Print diary version
.TP
\fB\-h\fR, \fB\-\-help\fR
Show diary help text
.TP
\fB\-d\fR, \fB\-\-dir\fR=\fI\,DIARY_DIR\/\fR
Diary storage directory DIARY_DIR
.TP
\fB\-r\fR, \fB\-\-range\fR=\fI\,RANGE\/\fR
RANGE is the number of years to show before/after todays date
.TP
\fB\-f\fR, \fB\-\-date_weekday\fR=\fI\,DAY\/\fR
First day of the week. DAY is an integer in range (0..6),
interpreted as 0 = Sun, 1 = Mon, ..., 6 = Sat
.TP
\fB\-f\fR, \fB\-\-fmt\fR=\fI\,FMT\/\fR
FMT is a custom date and file format. Change with care, because the diary
reads and writes to files with file name FMT. The new FMT is only
applied to newly saved entries. Existing entries with the old FMT are not
automatically migrated to the new FMT and do not show up with a new FMT
specifier. Consequently, a change in FMT shows an empty diary, at first.
Rename all files in the DIARY_DIR to migrate to a new FMT.

.SH ENVIRONMENT

.IP DIARY_DIR
If this variable is set to a directory that can be opened,
.B diary
will use it to store diary files. Diary files are simple text files named
after their date, formatted like FMT (see '-f'/'--fmt' options and
'fmt' config key). The format defaults to "%Y-%m-%d", which is "YYYY-MM-DD"
(see man strftime). All other files different from FMT are ignored.

.IP EDITOR
The program used to edit journal entries.

.SH ARGUMENTS

If the argument \fIDIRECTORY\fR is given, diary files are read from and
stored to that directory, ignoring the DIARY_DIR environment variable,
any '-d'/'--dir' options or the 'dir' value set in the config file.

.SH FILES
.TP
.I ${PREFIX:-/usr/local/bin}/diary
The diary binary
.TP
.I ${XDG_CONFIG_HOME:-~/.config}/diary/diary.cfg
An optional diary configuration file

.SH CONFIGURATION FILE
The diary.cfg configuration file can optionally be used to persist diary configuration.

Create default config location:

.nf
 $ mkdir -p ~/.config/diary
.fi

Install an example config file with defaults:

.nf
 $ echo '# Path that holds the journal text files
 #dir = ~/diary
 # Number of years to show before/after todays date
 range = 1
 # 0 = Sunday, 1 = Monday, ..., 6 = Saturday
 weekday = 1
 # Date and file format, change with care
 fmt = %Y-%m-%d' | sed 's/^[[:space:]]*//' > ~/.config/diary/diary.cfg
.fi

Use characters '#' or ';' for commenting lines.

.SH NAVIGATION
Navigation is done using the following vim-inspired keyboard shortcuts:

.TS
tab(|);
l l.
Key(s)    | Action
======    | ======
k, up     | go backward by 1 week
j, down   | go forward by 1 week
h, left   | go backward by 1 day
l, right  | go forward by 1 day
J         | go forward by 1 month
K         | go backward by 1 month

e, enter  | edit current entry
d, x      | delete current entry
q         | quit the program

N         | go to the previous journal entry
n         | go to the next journal entry
g         | go to the first journal entry
G         | go to the last journal entry

t         | jump to today
s         | jump to specific day
.TE


.SH DEVELOPMENT
All source code is available in this github repository:
<https://github.com/in0rdr/diary/>. Contributions are always welcome!
